Qwen/Qwen2.5-0.5B-Instruct:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 5
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05

Qwen/Qwen2.5-1.5B-Instruct:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.05

Qwen/Qwen2.5-7B-Instruct:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  num_train_epochs: 3
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.05
